require_relative 'stepping_piece'
require_relative 'sliding_piece'
require 'singleton'

require_relative 'piece'
require_relative 'bishop'
require_relative 'king'
require_relative 'knight'
require_relative 'null_piece'
require_relative 'pawn'
require_relative 'queen'
require_relative 'rook'
